version: '3.1'
services:
  scheduler:
    image: astrocrpublic.azurecr.io/runtime:3.3-7
    volumes:
      - /Users/hs086u/Documents/learning/terraform-projects/nyc-311-data-pipeline/dbtapp:/usr/local/airflow/dbtapp
      - /Users/hs086u/.dbt:/home/astro/.dbt
      - /Users/hs086u/Documents/learning/terraform-projects/nyc-311-data-pipeline/dbt-env:/usr/local/airflow/dbt-env
  webserver:
    image: astrocrpublic.azurecr.io/runtime:3.3-7
    volumes:
      - /Users/hs086u/Documents/learning/terraform-projects/nyc-311-data-pipeline/dbtapp:/usr/local/airflow/dbtapp
      - /Users/hs086u/.dbt:/home/astro/.dbt
      - /Users/hs086u/Documents/learning/terraform-projects/nyc-311-data-pipeline/dbt-env:/usr/local/airflow/dbt-env
  triggerer:
    image: astrocrpublic.azurecr.io/runtime:3.3-7
    volumes:
      - /Users/hs086u/Documents/learning/terraform-projects/nyc-311-data-pipeline/dbtapp:/usr/local/airflow/dbtapp
      - /Users/hs086u/.dbt:/home/astro/.dbt
      - /Users/hs086u/Documents/learning/terraform-projects/nyc-311-data-pipeline/dbt-env:/usr/local/airflow/dbt-env